spring.config.import=optional:file:.env[.properties]

spring.application.name=backend
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret Key
jwt.secret.key=${JWT_SECRET_KEY}

# ADMIN Account Info
# CHANGE THIS TO ACTUAL ADMIN INFO (CURRENTLY USING MY OWN FOR TESTING)
admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PASSWORD}
admin.phoneNumber=${ADMIN_PHONE_NUMBER}

# AWS S3 Settings
aws.access.key=${AWS_ACCESS_KEY_ID}
aws.secret.key=${AWS_SECRET_ACCESS_KEY}
aws.region=${AWS_REGION}
aws.bucket.name=${AWS_BUCKET_NAME}